import { App } from '@modelcontextprotocol/ext-apps';
const query=new URLSearchParams(location.search);
const web=query.get('mode')==='web';
const app=new App({name:'MCP Studio',version:'1.0.0'},{},{autoResize:true});
const el=(id:string)=>document.getElementById(id)!;
let ready=web;
let latest:Record<string,unknown>|undefined;
async function call(name:string,args:Record<string,unknown>={}){
 if(!ready)throw Error('Host is not connected yet.');
 if(!web)return app.callServerTool({name,arguments:args});
 const response=await fetch('/api/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:Date.now(),method:'tools/call',params:{name,arguments:args}})});const data:any=await response.json();if(data.error)throw Error(data.error.message);return data.result;
}
const palettes:Record<string,string[]>={analytics:['#17130f','#fff8ec','#322a20'],commerce:['#fff7ed','#221d1a','#ffd9ce'],fleet:['#111611','#eafbd6','#273127'],clinic:['#f8f7ff','#292547','#e8e4ff'],fintech:['#10221a','#eaffdf','#214031']};
function applyPalette(node:HTMLElement,template:any){const palette=palettes[template.id]??palettes.analytics;node.style.setProperty('--accent',template.accent);node.style.setProperty('--thumb-bg',palette[0]);node.style.setProperty('--thumb-ink',palette[1]);node.style.setProperty('--thumb-panel',palette[2]);node.style.setProperty('--stage-bg',palette[0]);node.style.setProperty('--stage-ink',palette[1]);node.style.setProperty('--stage-panel',palette[2]);}
function addPanels(node:HTMLElement,count:number){node.replaceChildren(...Array.from({length:count},()=>document.createElement('i')));}
function chooseTemplate(template:any){document.querySelectorAll('.templatecard').forEach(x=>x.classList.toggle('active',(x as HTMLElement).dataset.id===template.id));el('template-name').textContent=template.name;el('preview-title').textContent=template.name;el('template-desc').textContent=template.description;const preview=el('template-preview');preview.dataset.kind=template.id;applyPalette(preview,template);addPanels(el('preview-body'),template.id==='commerce'?6:template.id==='analytics'||template.id==='fintech'?5:template.id==='clinic'?5:2);const source=el('template-source') as HTMLAnchorElement;source.href=template.sourceUrl;source.textContent=`Inspired by ${template.author} on Dribbble ↗`;}
function showTemplates(data:any){const templates=data.templates??[];if(!templates.length)return;el('starter').setAttribute('hidden','');el('templates').classList.add('active');const grid=el('template-grid');grid.replaceChildren(...templates.map((template:any)=>{const button=document.createElement('button');button.className='templatecard';button.dataset.id=template.id;applyPalette(button,template);const thumb=document.createElement('div');thumb.className='thumb';thumb.dataset.kind=template.id;thumb.innerHTML='<span class="thumbtop"><span>Preview</span><em></em></span><span class="thumbbody"></span>';addPanels(thumb.querySelector('.thumbbody') as HTMLElement,template.id==='commerce'?3:template.id==='clinic'?5:2);const name=document.createElement('b');name.textContent=template.name;const category=document.createElement('small');category.textContent=template.category;button.appendChild(thumb);button.appendChild(name);button.appendChild(category);button.addEventListener('click',()=>chooseTemplate(template));return button}));chooseTemplate(templates.find((x:any)=>x.id===data.selection?.template)??templates[0]);if(data.selection?.theme)document.documentElement.dataset.theme=data.selection.theme;}
function show(data:any){if(!data)return;if(data.view==='template-builder'||data.templates)showTemplates(data);const a=data.estimate??data;if(typeof a.totalCost==='number'){latest=a;el('cost').textContent='$'+a.totalCost.toFixed(2);el('duration').textContent=a.sequentialSeconds.toFixed(1)+'s';el('requests').textContent=Number(a.requests).toLocaleString();} }
function report(error:unknown){el('status').textContent=String(error)}
app.ontoolresult=result=>show(result.structuredContent);
app.onhostcontextchanged=context=>{if(context.theme)document.documentElement.dataset.theme=context.theme};
(async()=>{try{if(web){el('mode').textContent='BROWSER MODE';const tool=query.get('view')==='templates'?'open_template_builder':'show_dashboard';show((await call(tool)).structuredContent)}else{await app.connect();ready=true;el('mode').textContent='HOST CONNECTED';if(app.getHostContext()?.theme)document.documentElement.dataset.theme=app.getHostContext()!.theme;}el('status').textContent='Ready to run your own assumptions.';if(!web)el('followup').removeAttribute('hidden')}catch(e){report(e)}})();
el('calculate').addEventListener('click',async e=>{e.preventDefault();if(!(el('estimate-form') as HTMLFormElement).reportValidity())return;const button=el('calculate') as HTMLButtonElement;button.disabled=true;el('status').textContent='Calculating…';try{const args={requests:Number((el('requests-input') as HTMLInputElement).value),latencyMs:Number((el('latency-input') as HTMLInputElement).value),costPerRequest:Number((el('cost-input') as HTMLInputElement).value)};const result=await call('calculate_estimate',args);if(result.isError)throw Error(result.content?.[0]?.text??'Tool rejected the request');show(result.structuredContent);el('status').textContent='Calculated from your inputs. No model tokens used.'}catch(e){report(e)}finally{button.disabled=false}});
el('followup').addEventListener('click',async()=>{try{await app.sendMessage({role:'user',content:[{type:'text',text:'Explain these usage assumptions and their limitations: '+JSON.stringify(latest??{})}]});el('status').textContent='Explanation requested in the conversation.'}catch(e){report(e)}});
el('light-theme').addEventListener('click',()=>document.documentElement.dataset.theme='light');
el('dark-theme').addEventListener('click',()=>document.documentElement.dataset.theme='dark');
