"use client";
import { useEffect, useState } from "react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Box, Code2, ArrowUpRight, Copy, Play, Check, FileCode2, Layers, Terminal, Download, RefreshCw } from "lucide-react";
import { promptDefinitions, resourceDefinitions, resourceTemplateDefinitions, toolDefinitions, RESOURCE_URI } from "@/lib/catalog";
import { TemplateBuilder } from "@/components/template-builder";
import { LayoutTemplate } from "lucide-react";

const MCP_ENDPOINT='/api/mcp';
const sampleArgs:Record<string,Record<string,unknown>>={calculate_estimate:{requests:1000,latencyMs:250,costPerRequest:0.002},open_template_builder:{template:'analytics',theme:'light'},search_catalog:{query:'resource',kind:'all'},validate_tool_input:{toolName:'calculate_estimate',input:{requests:1000,latencyMs:250,costPerRequest:0.002}},estimate_context_budget:{resourceCount:8,averageTokens:1200,contextWindow:128000},plan_workflow:{goal:'build'}};
async function callMcp(method:string,params:any){
 const response=await fetch(MCP_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:Date.now(),method,params})});
 const body=await response.text();
 const contentType=response.headers.get('content-type')??'';
 if(!response.ok)throw new Error(`MCP request failed (${response.status} ${response.statusText}) at ${MCP_ENDPOINT}${body?`: ${body.slice(0,180)}`:''}`);
 if(!contentType.includes('application/json'))throw new Error(`MCP returned ${contentType||'an unknown content type'} instead of JSON at ${MCP_ENDPOINT}${body?`: ${body.slice(0,180)}`:''}`);
 try{return JSON.parse(body)}catch{throw new Error(`MCP returned malformed JSON at ${MCP_ENDPOINT}: ${body.slice(0,180)||'empty response'}`)}
}
export default function Home(){
 const [tab,setTab]=useState('playground'); const [tool,setTool]=useState('show_dashboard');const [args,setArgs]=useState('{}'); const [result,setResult]=useState<any>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [ms,setMs]=useState<number|null>(null);const [origin,setOrigin]=useState('');const [copied,setCopied]=useState(false);const [frame,setFrame]=useState(0);
 useEffect(()=>setOrigin(location.origin),[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();for(const definition of toolDefinitions){try{Promise.resolve(context.registerTool({...definition,async execute(input:unknown){const data:any=await callMcp('tools/call',{name:definition.name,arguments:input});if(data.error||data.result?.isError)throw Error(data.error?.message??data.result?.content?.[0]?.text??'Invalid tool input');setTool(definition.name);setArgs(JSON.stringify(input,null,2));setResult(data.result);setTab('playground');return data.result;}},{signal:lifecycle.signal})).catch(()=>{});}catch{}}return()=>lifecycle.abort()},[]);
 async function run(method='tools/call',params:any={name:tool,arguments:JSON.parse(args)}){setBusy(true);setError('');setResult(null);setMs(null);const start=performance.now();try{const data:any=await callMcp(method,params);if(data.error||data.result?.isError)throw Error(data.error?.message??data.result?.content?.[0]?.text??'The MCP tool rejected this request.');setResult(data.result);setMs(Math.round(performance.now()-start));}catch(e){setError(e instanceof Error?e.message:String(e));setMs(Math.round(performance.now()-start))}finally{setBusy(false)}}
 async function copy(){try{await navigator.clipboard.writeText(origin+'/api/mcp');setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setError('Copy unavailable. Select the endpoint text to copy it.')}}
 function select(name:string){setTool(name);setArgs(JSON.stringify(sampleArgs[name]??{},null,2));setResult(null);setError('')}
 return <main className="studio"><header className="topbar"><a className="brand" href="/"><span className="brandmark"><Box size={22}/></span>MCP <b>Studio</b><span className="edition">STARTER / 01</span></a><a className="docslink" href="https://developers.openai.com/plugins/build/chatgpt-ui" target="_blank" rel="noreferrer">OpenAI docs <ArrowUpRight size={15}/></a></header>
 <div className="intro"><div><div className="eyebrow">WEB + CHATGPT · ONE INTERFACE</div><h1>Your first plugin,<br className="mobile-break"/> made tangible.</h1><p>Run a tool. Inspect the response. Put an interactive UI inside a conversation.</p></div><a className="download" href="/starter.zip" download><Download size={17}/> Download starter</a></div>
 <div className="endpoint"><span className="endpoint-label">MCP ENDPOINT</span><code>{origin || 'Your site origin'}/api/mcp</code><Button variant="ghost" size="sm" onClick={copy} aria-label="Copy MCP endpoint">{copied?<Check size={16}/>:<Copy size={16}/>}</Button><span className="transport">Streamable HTTP</span></div>
 <Tabs value={tab} onValueChange={setTab}><div className="tabrow"><TabsList variant="line"><TabsTrigger value="playground"><Play/> Playground</TabsTrigger><TabsTrigger value="templates"><LayoutTemplate/> Templates <span className="count">5</span></TabsTrigger><TabsTrigger value="tools"><Terminal/> Tools <span className="count">{toolDefinitions.length}</span></TabsTrigger><TabsTrigger value="resources"><Layers/> Resources <span className="count">{resourceDefinitions.length}</span></TabsTrigger><TabsTrigger value="prompts"><FileCode2/> Prompts <span className="count">{promptDefinitions.length}</span></TabsTrigger><TabsTrigger value="guide"><FileCode2/> Get started</TabsTrigger></TabsList><span className="quiet">No API key needed for examples</span></div>
 <TabsContent value="playground"><div className="workspace"><section className="controls"><div className="section-label">01 / CHOOSE A TOOL</div>{toolDefinitions.map((t,i)=><button key={t.name} onClick={()=>select(t.name)} className={'toolcard '+(tool===t.name?'selected':'')}><span className="toolnumber">0{i+1}</span><div><b>{t.title}</b><p>{t.description}</p><code>{t.name}</code></div>{tool===t.name&&<span className="selection-dot"/>}</button>)}<div className="tip"><Code2 size={18}/><p>These calls reach the real MCP server. Only the render tool opens a UI.</p></div></section>
 <section className="canvas"><div className="paneheader"><span><span className="dot"/> BROWSER PREVIEW</span><Button variant="ghost" size="sm" onClick={()=>setFrame(x=>x+1)} aria-label="Reload preview"><RefreshCw size={15}/></Button></div><div className="conversation"><div className="userbubble">Open the starter dashboard</div><div className="assistantlabel"><span className="mini-brand"><Box size={14}/></span> MCP Studio <span>Example conversation</span></div><iframe key={frame} title="Interactive MCP widget" src="/widget?mode=web" sandbox="allow-scripts allow-same-origin"/><p className="previewnote">Same UI resource, two runtimes. Here it calls /api/mcp; in ChatGPT it uses the host bridge.</p></div><div className="canvasfooter"><span>ui://starter/dashboard.html</span><span>Interactive resource</span></div></section>
 <section className="inspector"><div className="section-label">02 / INSPECT THE CONTRACT</div><label htmlFor="arguments">Tool arguments <span>JSON</span></label><textarea id="arguments" value={args} onChange={e=>setArgs(e.target.value)} spellCheck={false}/><Button className="runbutton" disabled={busy} onClick={()=>{try{JSON.parse(args);run()}catch{setError('Enter a valid JSON object.')}}}><Play size={15}/>{busy?'Running…':'Run tool'}</Button><div className="responsehead"><b>Response</b><span>{ms!==null?ms+' ms':'Awaiting call'}</span></div>{error&&<p className="error" role="alert">{error}</p>}<pre className="response" aria-live="polite">{result?JSON.stringify(result,null,2):'// Run a tool to inspect\n// its structured response.'}</pre><div className="contract"><span>READ ONLY</span><p>Validated inputs. Structured output. No external service calls.</p></div></section></div></TabsContent>
 <TabsContent value="tools"><div className="reference"><h2>Small tools. Clear contracts.</h2><p>Data tools return useful results on their own. A dedicated render tool attaches the UI.</p>{toolDefinitions.map(t=><article className="referencecard" key={t.name}><h3>{t.title} <code>{t.name}</code></h3><p>{t.description}</p><pre>{JSON.stringify(t,null,2)}</pre><Button variant="outline" onClick={()=>{select(t.name);setTab('playground')}}>Try this tool <Play size={14}/></Button></article>)}</div></TabsContent>
 <TabsContent value="templates"><TemplateBuilder/></TabsContent>
 <TabsContent value="resources"><div className="reference"><h2>Context, addressed by URI.</h2><p>Eight concrete resources and three parameterized templates demonstrate discovery, reads, links, annotations, and completion. The <code>mcp://</code> scheme is intentionally custom and RFC 3986 compliant, not protocol mandated.</p><div className="actions"><Button onClick={()=>run('resources/list',{})}>List resources</Button><Button variant="outline" onClick={()=>run('resources/templates/list',{})}>List templates</Button><Button variant="outline" onClick={()=>run('completion/complete',{ref:{type:'ref/resource',uri:'mcp://studio/tool/{name}'},argument:{name:'name',value:'get_'}})}>Complete tool URI</Button></div>{resourceDefinitions.map(resource=><article className="referencecard" key={resource.uri}><h3>{resource.title} <code>{resource.name}</code></h3><p>{resource.description}</p><code>{resource.uri}</code><p>Content type: {resource.mimeType}</p><Button variant="outline" onClick={()=>run('resources/read',{uri:resource.uri})}>Read resource</Button>{resource.uri===RESOURCE_URI&&<a href="/widget?mode=web" target="_blank" rel="noreferrer"> Open browser version ↗</a>}</article>)}<h2>Parameterized resources</h2>{resourceTemplateDefinitions.map(template=><article className="referencecard" key={template.uriTemplate}><h3>{template.title}</h3><p>{template.description}</p><code>{template.uriTemplate}</code></article>)}<pre>{result?JSON.stringify(result,null,2):'List, complete, or read a resource to inspect its MCP response.'}</pre></div></TabsContent>
 <TabsContent value="prompts"><div className="reference"><h2>User controlled prompt templates.</h2><p>Prompts are discoverable workflows, separate from model controlled tools and application controlled resources.</p><div className="actions"><Button onClick={()=>run('prompts/list',{})}>List prompts</Button></div>{promptDefinitions.map(prompt=><article className="referencecard" key={prompt.name}><h3>{prompt.title} <code>{prompt.name}</code></h3><p>{prompt.description}</p><Button variant="outline" onClick={()=>run('prompts/get',{name:prompt.name,arguments:prompt.name==='design_mcp_tool'?{goal:'Build a governed search tool'}:prompt.name==='plan_mcp_app'?{audience:'operations leaders'}:{focus:'authorization and data exposure'}})}>Get prompt</Button></article>)}<pre>{result?JSON.stringify(result,null,2):'List or retrieve a prompt to inspect its messages.'}</pre></div></TabsContent>
 <TabsContent value="guide"><div className="reference guide"><div><div className="eyebrow">FROM BROWSER TO CONVERSATION</div><h2>Connect your first plugin.</h2><p>The browser playground runs deterministic examples. ChatGPT supplies the model and conversation when you connect the MCP server.</p>{[['1','Test the contract','Run each example in the playground. Use Tools to inspect input schemas and Resources to read the widget HTML.'],['2','Make the endpoint reachable','Sites starts private. A ChatGPT server cannot reuse your browser session. Publish with suitable public access for this harmless demo, or host the starter behind proper MCP OAuth. Do not assume a private Site URL can connect.'],['3','Connect in ChatGPT','In ChatGPT developer settings, add a remote MCP connection using the endpoint above. Select no authentication only when your deployed demo endpoint is intentionally public. Availability depends on your workspace.'],['4','Ask for the dashboard','Ask: “Use MCP Studio to show the starter dashboard.” Then run the estimate from the embedded card. The tool should return structured data and one interactive resource.']].map(([n,h,p])=><article className="step" key={n}><span>{n}</span><div><h3>{h}</h3><p>{p}</p></div></article>)}</div><aside className="guideaside"><h3>Make it yours</h3><p><code>lib/catalog.ts</code><br/>Schemas and example definitions</p><p><code>lib/api/mcp-server.ts</code><br/>Validated server handlers</p><p><code>widget/main.ts</code><br/>Embedded UI and host bridge</p><p><code>app/api/mcp/route.ts</code><br/>Streamable HTTP transport</p><p>Keep secrets and authorization on the server. Add authentication before introducing private data or write actions.</p><a href="https://developers.openai.com/plugins/build/chatgpt-ui" target="_blank" rel="noreferrer">Read the official UI guide ↗</a></aside></div></TabsContent>
 </Tabs><footer><span><Box size={14}/> A starting point, not a black box.</span><span>MCP Apps · Built for the web and the conversation</span></footer></main>
}
