"use client";

import { useState, type CSSProperties, type MouseEvent as ReactMouseEvent, type ReactNode } from "react";
import { dashboardTemplates, type TemplateId } from "@/lib/templates";
import { Button } from "@/components/ui/button";
import { Activity, ArrowRight, ArrowUpRight, Bell, Boxes, CalendarDays, Check, ChevronDown, CircleDollarSign, Clock3, Copy, ExternalLink, Gauge, HeartPulse, MapPin, Menu, Moon, MoreHorizontal, Search, Sparkles, Sun, Truck, Users, WalletCards } from "lucide-react";

function MiniLine({ color = "currentColor" }: { color?: string }) {
  const id = `fade-${color.replace("#", "")}`;
  return <svg className="mini-line" viewBox="0 0 360 120" role="img" aria-label="Rising revenue trend"><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={color} stopOpacity=".28"/><stop offset="1" stopColor={color} stopOpacity="0"/></linearGradient></defs><path className="chart-grid" d="M0 20H360M0 60H360M0 100H360"/><path fill={`url(#${id})`} d="M0 92C35 88 45 55 79 63S126 90 157 61s41-47 76-28 44 42 74 18 35-25 53-32v101H0Z"/><path className="chart-line" stroke={color} d="M0 92C35 88 45 55 79 63S126 90 157 61s41-47 76-28 44 42 74 18 35-25 53-32"/></svg>;
}

function NavIcon({ active, children }: { active?: boolean; children: ReactNode }) { return <button className={active ? "nav-icon active" : "nav-icon"}>{children}</button>; }

function AnalyticsSurface() {
  return <div className="surface analytics-surface"><aside className="a-side"><div className="a-logo"><Sparkles/></div><div className="a-nav"><NavIcon active><Gauge/></NavIcon><NavIcon><Activity/></NavIcon><NavIcon><Users/></NavIcon><NavIcon><Boxes/></NavIcon></div><div className="avatar amber">RV</div></aside><main className="a-main"><header className="surface-head"><div><span>MONDAY, 17 SEPTEMBER</span><h3>Good morning, Reuven.</h3></div><div className="head-actions"><button><Search/></button><button><Bell/></button><div className="avatar">RV</div></div></header><div className="a-summary"><article className="hero-metric"><span>NET REVENUE</span><strong>$184,830</strong><p><b>+24.6%</b> against last month</p><MiniLine color="#ffb45c"/></article><article className="a-score"><div><span>GOAL PROGRESS</span><MoreHorizontal/></div><div className="orb"><strong>82%</strong><small>On track</small></div><p>$184.8k of $225k target</p></article></div><div className="a-kpis">{[["Customers","12,840","+8.2%"],["Avg. order","$148.20","+3.4%"],["Churn","1.84%","−0.6%"]].map(([label,value,delta])=><article key={label}><span>{label}</span><strong>{value}</strong><em>{delta}</em></article>)}</div><div className="a-table"><header><b>Market performance</b><button>View report <ArrowUpRight/></button></header>{["North America","Europe","Asia Pacific"].map((name,i)=><div key={name}><span className={`region r${i}`}/><b>{name}</b><span>{[42,31,18][i]}%</span><i><em style={{width:`${[86,67,48][i]}%`}}/></i><strong>{["$28.9k","$41.7k","$38.2k"][i]}</strong></div>)}</div></main></div>;
}

function CommerceSurface() {
  return <div className="surface commerce-surface"><header className="c-head"><div className="c-logo">ora<span>·</span></div><nav><b>Overview</b><span>Products</span><span>Orders</span><span>Customers</span></nav><div className="head-actions"><button><Search/></button><button><Bell/></button><div className="avatar coral">LM</div></div></header><main className="c-main"><div className="c-title"><div><span>STORE OVERVIEW</span><h3>Everything moving today.</h3></div><button className="pill-button">Add product <span>＋</span></button></div><div className="c-metrics"><article className="c-feature"><span>TOTAL SALES</span><strong>$48,624</strong><p><b>18.4%</b> from yesterday</p><div className="c-bars">{[28,43,35,62,49,76,68,88,72,96].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></article>{[["Orders","1,284","68 new"],["Conversion","4.82%","0.7% up"],["Returns","2.1%","Healthy"]].map(([l,v,d],i)=><article className={`c-stat c-stat-${i}`} key={l}><span>{l}</span><strong>{v}</strong><p>{d}</p><ArrowUpRight/></article>)}</div><div className="c-lower"><section><header><div><b>Best sellers</b><span>Last 7 days</span></div><button><MoreHorizontal/></button></header><div className="products">{[["Noma Lamp","Home","$129"],["Fold Chair","Studio","$214"],["Soft Clock","Living","$88"]].map(([n,c,p],i)=><article key={n}><div className={`product-art product-${i}`}><span/></div><b>{n}</b><small>{c}</small><strong>{p}</strong></article>)}</div></section><aside><header><b>Orders</b><span>Live</span></header>{[["#10482","Packing","AB"],["#10481","Ready","SK"],["#10480","Review","JL"]].map(([n,s,a],i)=><div key={n}><div className={`avatar soft a${i}`}>{a}</div><p><b>{n}</b><span>{s}</span></p><strong>{["$348","$219","$186"][i]}</strong></div>)}<button className="text-button">Open order queue <ArrowRight/></button></aside></div></main></div>;
}

function FleetSurface() {
  return <div className="surface fleet-surface"><header className="f-head"><div className="f-brand"><Truck/> VANTA</div><nav><b>Dispatch</b><span>Fleet</span><span>Drivers</span><span>Analytics</span></nav><div className="live-chip"><i/> 24 vehicles live</div><div className="avatar lime">RC</div></header><main className="f-main"><section className="map-panel"><div className="map-grid"/><span className="road road-a"/><span className="road road-b"/><span className="road road-c"/><span className="road road-d"/>{[["p1","204"],["p2","118"],["p3","042"],["p4","216"]].map(([p,n])=><button className={`fleet-pin ${p}`} key={p}><Truck/><b>{n}</b></button>)}<div className="map-toolbar"><button><Search/></button><button><MapPin/></button></div><div className="map-callout"><span>TRUCK 204</span><b>12 min ahead</b><p>Toronto → Oakville</p><button>Inspect route <ArrowUpRight/></button></div></section><aside className="dispatch-rail"><div className="dispatch-title"><span>LIVE DISPATCH</span><h3>Morning routes</h3><p>183 of 212 drops complete</p></div><div className="fleet-ring"><div><strong>86%</strong><span>delivered</span></div></div><div className="route-list">{[["TRK 204","12 min early","86%"],["TRK 118","On schedule","62%"],["VAN 042","4 min late","41%"]].map(([n,s,p],i)=><article key={n}><header><div className={`driver driver-${i}`}/><p><b>{n}</b><span>{s}</span></p><MoreHorizontal/></header><div><i style={{width:p}}/></div><footer><span>{["18","12","9"][i]} stops</span><strong>{["Oakville","Hamilton","Toronto"][i]}</strong></footer></article>)}</div><button className="dispatch-button">Optimize all routes <Sparkles/></button></aside></main></div>;
}

function ClinicSurface() {
  const days=["Mon 14","Tue 15","Wed 16","Thu 17","Fri 18"];
  const appointments:Record<number,[string,string,string]>={1:["09:30","Nina Patel","checkup"],3:["10:00","Sam Lee","followup"],6:["11:30","Alex Morgan","consult"],9:["13:00","Mia Chen","checkup"],11:["14:30","Noah Smith","consult"],13:["15:00","Lena Park","followup"]};
  return <div className="surface clinic-surface"><aside className="h-side"><div className="h-brand"><HeartPulse/> Halcyon</div><nav><button className="active"><CalendarDays/> Appointments</button><button><Users/> Patients</button><button><Clock3/> Availability</button><button><Activity/> Insights</button></nav><div className="doctor"><div className="avatar violet">DR</div><p><b>Dr. Rivera</b><span>Cardiology</span></p><ChevronDown/></div></aside><main className="h-main"><header className="surface-head"><div><span>WEEK 38</span><h3>Appointments</h3></div><div className="head-actions"><button><Search/></button><button><Bell/></button><button className="new-appointment">New appointment</button></div></header><div className="h-overview"><article><div className="h-icon violet-bg"><CalendarDays/></div><p><span>Today</span><strong>12 visits</strong></p><em>4 remaining</em></article><article><div className="h-icon aqua-bg"><Users/></div><p><span>New patients</span><strong>18 this month</strong></p><em>+12%</em></article><article><div className="h-icon peach-bg"><Clock3/></div><p><span>Utilization</span><strong>84% booked</strong></p><em>Healthy</em></article></div><section className="h-schedule"><header><div><b>September 14 – 18</b><span>Weekly schedule</span></div><div><button>‹</button><button>›</button></div></header><div className="h-days">{days.map(d=><b key={d}>{d}</b>)}</div><div className="h-calendar">{Array.from({length:15},(_,i)=><div key={i}>{appointments[i]&&<article className={appointments[i][2]}><span>{appointments[i][0]}</span><b>{appointments[i][1]}</b><small>{appointments[i][2]}</small></article>}</div>)}</div></section></main></div>;
}

function FintechSurface() {
  return <div className="surface fintech-surface"><aside className="l-side"><div className="l-logo"><CircleDollarSign/></div><nav><NavIcon active><Gauge/></NavIcon><NavIcon><WalletCards/></NavIcon><NavIcon><Activity/></NavIcon><NavIcon><Users/></NavIcon></nav><button className="l-help">?</button></aside><main className="l-main"><header className="surface-head"><div><span>ACME OPERATIONS</span><h3>Financial overview</h3></div><div className="head-actions"><button><Search/></button><button><Bell/></button><div className="avatar navy">RC</div></div></header><div className="l-balance"><section><span>AVAILABLE BALANCE</span><strong>$148,620.40</strong><p><b>+8.2%</b> since August</p><div className="l-actions"><button>Send money <ArrowUpRight/></button><button>Request</button></div></section><aside><div><span>CARD SPEND</span><b>$24,820</b></div><div><span>MONTHLY LIMIT</span><b>$40,000</b></div><i><em/></i><p>62% of limit used</p></aside></div><div className="l-grid"><section className="cash-chart"><header><div><b>Cash flow</b><span>Last 7 months</span></div><strong>+$42,184</strong></header><MiniLine color="#9df284"/><div className="chart-labels">{["MAR","APR","MAY","JUN","JUL","AUG","SEP"].map(x=><span key={x}>{x}</span>)}</div></section><aside className="spend"><header><b>Spend by team</b><button><MoreHorizontal/></button></header>{[["Product","42%"],["Growth","31%"],["Operations","18%"]].map(([n,p],i)=><div key={n}><span className={`team t${i}`}/><p><b>{n}</b><span>{p} of spend</span></p><strong>{["$10,420","$7,694","$4,468"][i]}</strong></div>)}</aside></div><section className="l-transactions"><header><b>Recent transactions</b><button>See all <ArrowRight/></button></header>{[["Cloud North","Infrastructure","− $4,820"],["Linear Systems","Software","− $1,248"],["Acme Retail","Revenue","+ $18,400"]].map(([n,c,v],i)=><div key={n}><span className={`merchant m${i}`}>{n[0]}</span><p><b>{n}</b><span>{c}</span></p><small>SEP {17-i}</small><strong className={i===2?"positive":""}>{v}</strong></div>)}</section></main></div>;
}

function TemplateSurface({ id }: { id: TemplateId }) { if(id==="commerce")return <CommerceSurface/>;if(id==="fleet")return <FleetSurface/>;if(id==="clinic")return <ClinicSurface/>;if(id==="fintech")return <FintechSurface/>;return <AnalyticsSurface/>; }

export function TemplateBuilder(){
  const [selected,setSelected]=useState<TemplateId>("analytics");const [dark,setDark]=useState(false);const [copied,setCopied]=useState(false);const [action,setAction]=useState("");const [previewMenu,setPreviewMenu]=useState(false);const current=dashboardTemplates.find(template=>template.id===selected)!;const style={"--template-accent":current.accent} as CSSProperties;
  async function copy(){await navigator.clipboard.writeText(JSON.stringify({tool:"open_template_builder",arguments:{template:selected,theme:dark?"dark":"light"}},null,2));setCopied(true);setTimeout(()=>setCopied(false),1500)}
  function handleSurfaceAction(event:ReactMouseEvent<HTMLElement>){const button=(event.target as HTMLElement).closest("button");if(!button)return;const icon=button.querySelector("svg")?.getAttribute("class")?.match(/lucide-([^ ]+)/)?.[1]?.replaceAll("-"," ");const label=button.getAttribute("aria-label")||button.textContent?.trim()||icon||"Control";if(label==="Preview menu"){setPreviewMenu(value=>!value);return}if(label==="Dismiss action"){setAction("");return}if(label==="Reset preview"){setSelected("analytics");setDark(false);setPreviewMenu(false);setAction("Preview reset to Signal Analytics in light mode.");return}if(label==="Open full screen"){setPreviewMenu(false);void event.currentTarget.requestFullscreen?.().catch(()=>setAction("Full screen is blocked by this browser host."));setAction("Full screen preview opened.");return}setPreviewMenu(false);setAction(`${label.charAt(0).toUpperCase()+label.slice(1)} opened in the ${current.name} demo.`)}
  return <div className="templatebuilder" style={style}><div className="templatehead"><div><div className="eyebrow">MCP EMBED TEMPLATE GALLERY</div><h2>Five products. Five design languages.</h2><p>Production-ready surfaces for structured tool data, responsive embeds, and host actions.</p></div><div className="themecontrol" role="group" aria-label="Preview theme"><button className={!dark?"active":""} onClick={()=>setDark(false)}><Sun/> Light</button><button className={dark?"active":""} onClick={()=>setDark(true)}><Moon/> Dark</button></div></div><div className="templatework"><nav aria-label="Dashboard templates">{dashboardTemplates.map((template,index)=><button key={template.id} className={selected===template.id?"active":""} onClick={()=>{setSelected(template.id);setAction("");setPreviewMenu(false)}}><span className="template-number">0{index+1}</span><div><b>{template.name}</b><small>{template.category}</small></div><i style={{background:template.accent}}/></button>)}</nav><section className={`templatepreview ${dark?"dark":"light"}`} onClickCapture={handleSurfaceAction}><div className="previewchrome"><div><span/><span/><span/></div><b>{current.name}</b><small>RESPONSIVE MCP EMBED</small><button aria-label="Preview menu"><Menu/></button>{previewMenu&&<div className="preview-menu"><button>Open full screen</button><button>Reset preview</button></div>}</div><TemplateSurface id={selected}/>{action&&<div className="surface-feedback" role="status" aria-live="polite"><Check/><span>{action}</span><button aria-label="Dismiss action">×</button></div>}</section><aside className="templateinfo"><span className="templateindex">0{dashboardTemplates.findIndex(x=>x.id===selected)+1} / 05</span><span className="category-chip">{current.category}</span><h3>{current.name}</h3><p>{current.description}</p><dl><div><dt>Theme</dt><dd>{dark?"Dark":"Light"}</dd></div><div><dt>Layout</dt><dd>Adaptive</dd></div><div><dt>Tool state</dt><dd>Interactive</dd></div></dl><Button onClick={copy}>{copied?<Check/>:<Copy/>}{copied?"Copied":"Copy MCP call"}</Button><a href={current.sourceUrl} target="_blank" rel="noreferrer"><span>Design reference</span><strong>{current.sourceTitle}</strong><small>by {current.author} <ExternalLink/></small></a></aside></div><div className="attribution"><b>Original design references</b>{dashboardTemplates.map(template=><a key={template.id} href={template.sourceUrl} target="_blank" rel="noreferrer">{template.author}<ExternalLink/></a>)}</div></div>;
}
