"use client";
import {useState} from 'react';
import {dashboardTemplates,TemplateId} from '@/lib/templates';
import {Button} from '@/components/ui/button';
import {Moon,Sun,ExternalLink,Copy,Check,PanelLeft,Search,Bell,ArrowUpRight,Truck,CalendarDays,WalletCards,ShoppingBag,ChartNoAxesCombined} from 'lucide-react';

function Spark({accent}:{accent:string}){return <div className="spark" aria-label="Upward trend chart"><i style={{height:'24%',background:accent}}/><i style={{height:'42%',background:accent}}/><i style={{height:'35%',background:accent}}/><i style={{height:'66%',background:accent}}/><i style={{height:'58%',background:accent}}/><i style={{height:'86%',background:accent}}/><i style={{height:'74%',background:accent}}/></div>}
function Shell({id,accent}:{id:TemplateId,accent:string}){
 const icons={analytics:<ChartNoAxesCombined/>,commerce:<ShoppingBag/>,fleet:<Truck/>,clinic:<CalendarDays/>,fintech:<WalletCards/>};
 return <div className={'dashmock dash-'+id}>
  <aside><b className="mocklogo">{icons[id]}</b><i/><i/><i/><i/><span/></aside>
  <div className="dashmain"><header><div><small>Workspace</small><b>{id==='analytics'?'Performance overview':id==='commerce'?'Order operations':id==='fleet'?'Live dispatch':id==='clinic'?'Appointments': 'Financial overview'}</b></div><div className="mockactions"><Search/><Bell/><span>RC</span></div></header>
  {id==='clinic'?<Clinic accent={accent}/>:id==='fleet'?<Fleet accent={accent}/>:id==='commerce'?<Commerce accent={accent}/>:<Metrics accent={accent} fintech={id==='fintech'}/>}</div>
 </div>
}
function Metrics({accent,fintech}:{accent:string,fintech:boolean}){return <><div className="metricrow"><article><small>{fintech?'Current balance':'Total revenue'}</small><strong>{fintech?'$148,620':'$86,241'}</strong><em>+12.4%</em></article><article><small>{fintech?'Money in':'Active users'}</small><strong>{fintech?'$24,820':'18,429'}</strong><em>+8.1%</em></article><article><small>{fintech?'Money out':'Conversion'}</small><strong>{fintech?'$9,430':'24.8%'}</strong><em>+3.2%</em></article></div><div className="mockgrid"><article className="trend"><div><small>{fintech?'Cash flow':'Revenue growth'}</small><b>Last 7 months</b></div><Spark accent={accent}/></article><article className="ring"><small>{fintech?'Spending limit':'Goal progress'}</small><div style={{background:`conic-gradient(${accent} 0 74%,var(--mock-muted) 74%)`}}><b>74%</b></div><p>On track this month</p></article></div><div className="mocktable"><b>{fintech?'Top merchants':'Recent activity'}</b>{['Arc Systems','Northwind Labs','Meridian Group'].map((x,i)=><div key={x}><span>{x}</span><i/><small>{['$12,840','$8,420','$6,960'][i]}</small></div>)}</div></>}
function Commerce({accent}:{accent:string}){return <><div className="metricrow"><article><small>Orders today</small><strong>1,284</strong><em>+18%</em></article><article><small>In fulfillment</small><strong>318</strong><em>42 urgent</em></article><article><small>Inventory alerts</small><strong>14</strong><em>Review</em></article></div><div className="commercebody"><div className="mocktable"><b>Order queue</b>{['#10482 · Lumon',' #10481 · Aster',' #10480 · Noma'].map((x,i)=><div key={x}><span>{x}</span><i style={{background:accent}}/><small>{['Packing','Ready','Review'][i]}</small></div>)}</div><article className="orderrail"><small>SELECTED ORDER</small><strong>#10482</strong><p>3 products · Express delivery</p><button>Open details <ArrowUpRight/></button></article></div></>}
function Fleet({accent}:{accent:string}){return <><div className="fleetgrid"><article className="mapmock"><span className="road r1"/><span className="road r2"/><span className="road r3"/>{[1,2,3,4].map(n=><i key={n} className={'pin p'+n} style={{background:accent}}/>)}<b>24 active routes</b></article><article className="fleetstats"><small>Completion rate</small><strong>86%</strong><div><i style={{width:'86%',background:accent}}/></div><p>183 of 212 orders delivered</p></article></div><div className="mocktable"><b>Active deliveries</b>{['TRK 204 · Toronto','TRK 118 · Hamilton','VAN 42 · Oakville'].map((x,i)=><div key={x}><span>{x}</span><i style={{background:accent}}/><small>{['12 min','28 min','41 min'][i]}</small></div>)}</div></>}
function Clinic({accent}:{accent:string}){const days=['Mon 14','Tue 15','Wed 16','Thu 17','Fri 18'];return <><div className="calendarhead">{days.map(x=><b key={x}>{x}</b>)}</div><div className="calendargrid">{Array.from({length:15},(_,i)=><div key={i}>{[1,3,6,9,11,13].includes(i)&&<span style={{background:i%2?accent:'#55a6a6'}}>{i%2?'Consultation':'Follow up'}<small>{9+i%4}:30</small></span>}</div>)}</div><div className="patientbar"><span style={{background:accent}}>AM</span><div><b>Alex Morgan</b><small>Annual consultation · 10:30</small></div><button>View patient</button></div></>}

export function TemplateBuilder(){const [selected,setSelected]=useState<TemplateId>('analytics');const [dark,setDark]=useState(false);const [copied,setCopied]=useState(false);const current=dashboardTemplates.find(x=>x.id===selected)!;async function copy(){await navigator.clipboard.writeText(JSON.stringify({tool:'open_template_builder',arguments:{template:selected,theme:dark?'dark':'light'}},null,2));setCopied(true);setTimeout(()=>setCopied(false),1500)}return <div className="templatebuilder">
 <div className="templatehead"><div><div className="eyebrow">MCP EMBED TEMPLATE BUILDER</div><h2>Choose a working surface.</h2><p>Five responsive patterns, ready for tool data and the ChatGPT host bridge.</p></div><div className="themecontrol" role="group" aria-label="Preview theme"><button className={!dark?'active':''} onClick={()=>setDark(false)}><Sun/> Light</button><button className={dark?'active':''} onClick={()=>setDark(true)}><Moon/> Dark</button></div></div>
 <div className="templatework"><nav aria-label="Dashboard templates">{dashboardTemplates.map(t=><button key={t.id} className={selected===t.id?'active':''} onClick={()=>setSelected(t.id)}><span style={{background:t.accent}}/><div><b>{t.name}</b><small>{t.category}</small></div></button>)}</nav><section className={'templatepreview '+(dark?'dark':'light')}><div className="previewchrome"><span/><span/><span/><b>{current.name} · ChatGPT embed preview</b></div><Shell id={selected} accent={current.accent}/></section><aside className="templateinfo"><span className="templateindex">0{dashboardTemplates.findIndex(x=>x.id===selected)+1} / 05</span><h3>{current.name}</h3><p>{current.description}</p><dl><div><dt>Theme</dt><dd>{dark?'Dark':'Light'}</dd></div><div><dt>Embed</dt><dd>Responsive</dd></div><div><dt>Tool state</dt><dd>Structured</dd></div></dl><Button onClick={copy}>{copied?<Check/>:<Copy/>}{copied?'Copied':'Copy MCP call'}</Button><a href={current.sourceUrl} target="_blank" rel="noreferrer">Inspired by {current.sourceTitle}<strong>{current.author} <ExternalLink/></strong></a></aside></div>
 <div className="attribution"><b>Design references</b>{dashboardTemplates.map(t=><a key={t.id} href={t.sourceUrl} target="_blank" rel="noreferrer">{t.author}<ExternalLink/></a>)}</div>
 </div>}
