import { McpServer, ResourceTemplate } from '@modelcontextprotocol/sdk/server/mcp.js';
import { registerAppTool, registerAppResource, RESOURCE_MIME_TYPE } from '@modelcontextprotocol/ext-apps/server';
import { z } from 'zod';
import { examples, promptDefinitions, resourceDefinitions, resourceTemplateDefinitions, toolDefinitions, RESOURCE_URI } from './catalog';
import { widgetHtml } from './widget.generated';
import { dashboardTemplates } from './templates';

export const estimateSchema=z.object({requests:z.number().int().min(1).max(1000000),latencyMs:z.number().min(0).max(600000),costPerRequest:z.number().min(0).max(1000)}).strict();
const builderSchema=z.object({template:z.enum(['analytics','commerce','fleet','clinic','fintech']).optional(),theme:z.enum(['light','dark']).optional()}).strict();
const searchSchema=z.object({query:z.string().min(1).max(80),kind:z.enum(['all','tool','resource','template','prompt']).default('all')}).strict();
const validateSchema=z.object({toolName:z.string().min(1).max(128),input:z.record(z.string(),z.unknown())}).strict();
const budgetSchema=z.object({resourceCount:z.number().int().min(1).max(1000),averageTokens:z.number().int().min(1).max(1000000),contextWindow:z.number().int().min(1000).max(10000000)}).strict();
const workflowSchema=z.object({goal:z.enum(['build','audit','debug','optimize'])}).strict();
const emptySchema=z.object({}).strict();

const inputSchemas:Record<string,z.ZodType>={show_dashboard:emptySchema,get_examples:emptySchema,calculate_estimate:estimateSchema,list_embed_templates:emptySchema,open_template_builder:builderSchema,search_catalog:searchSchema,inspect_capabilities:emptySchema,validate_tool_input:validateSchema,estimate_context_budget:budgetSchema,plan_workflow:workflowSchema,get_resource_examples:emptySchema,get_security_checklist:emptySchema};
const securityChecks=['Validate every tool argument and resource URI','Authorize at execution time, not discovery time','Keep secrets and private data on the server','Require confirmation for consequential writes','Return least privilege annotations and honest side effect hints','Bound payload size, latency, fan out, and retries','Validate structured results against output schemas','Treat tool annotations and resource metadata as untrusted across trust boundaries','Log decisions without logging sensitive payloads','Test malformed JSON, unknown methods, oversized bodies, and cross origin behavior'];
const topicDocs:Record<string,string>={
 tools:'# Tools\n\nUse narrow names, precise descriptions, JSON Schema inputs, output schemas, honest annotations, bounded execution, and structured results with text fallbacks.',
 resources:'# Resources\n\nResources are application controlled context identified by RFC 3986 URIs. Prefer templates plus completion for large dynamic collections. Validate every URI before reading.',
 prompts:'# Prompts\n\nPrompts are user controlled reusable workflows. Validate arguments and keep instructions explicit, inspectable, and free of hidden authority.',
 completions:'# Completions\n\nReturn ranked, filtered suggestions for prompt arguments and resource template variables. Rate limit, validate prefixes, and prevent suggestion based information disclosure.',
 security:'# Security\n\nApply least privilege, execution time authorization, human confirmation for writes, payload bounds, audit logs, and explicit trust boundaries.',
};

export function estimate(input:unknown){const a=estimateSchema.parse(input);return {...a,totalCost:Math.round(a.requests*a.costPerRequest*1e6)/1e6,sequentialSeconds:a.requests*a.latencyMs/1000,currency:'USD',assumptions:'User supplied estimates, not measured performance or provider pricing.'};}
const result=(data:Record<string,unknown>)=>({content:[{type:'text' as const,text:JSON.stringify(data)}],structuredContent:data});
const jsonResource=(uri:string,data:unknown,mimeType='application/json')=>({contents:[{uri,mimeType,text:JSON.stringify(data,null,2)}]});
const markdownResource=(uri:string,text:string)=>({contents:[{uri,mimeType:'text/markdown',text}]});
const annotations={audience:['user','assistant'] as ('user'|'assistant')[],priority:0.8,lastModified:'2026-09-17T21:45:00Z'};

function catalogEntries(){return [
 ...toolDefinitions.map(x=>({kind:'tool',name:x.name,title:x.title,description:x.description})),
 ...resourceDefinitions.map(x=>({kind:'resource',name:x.name,title:x.title,description:x.description,uri:x.uri})),
 ...resourceTemplateDefinitions.map(x=>({kind:'template',name:x.name,title:x.title,description:x.description,uri:x.uriTemplate})),
 ...promptDefinitions.map(x=>({kind:'prompt',name:x.name,title:x.title,description:x.description})),
];}

function staticResource(uri:string){
 if(uri==='mcp://studio/manifest')return jsonResource(uri,{name:'mcp-studio',referenceSpec:'2025-11-25',customScheme:{scheme:'mcp',portable:true,standardRequired:false},counts:{tools:toolDefinitions.length,resources:resourceDefinitions.length,resourceTemplates:resourceTemplateDefinitions.length,prompts:promptDefinitions.length},capabilities:['tools','resources','resourceTemplates','prompts','completions','mcpApps']});
 if(uri==='mcp://studio/tools/catalog')return jsonResource(uri,{tools:toolDefinitions});
 if(uri==='mcp://studio/templates/catalog')return jsonResource(uri,{templates:dashboardTemplates});
 if(uri==='mcp://studio/examples/tool-call')return markdownResource(uri,'# Tool call\n\n```json\n{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"calculate_estimate","arguments":{"requests":1000,"latencyMs":250,"costPerRequest":0.002}}}\n```\n\nThe result includes both text content and structuredContent for compatibility.');
 if(uri==='mcp://studio/examples/resource-flow')return markdownResource(uri,'# Resource flow\n\n1. Call `resources/list`.\n2. Call `resources/templates/list`.\n3. Call `completion/complete` for a template variable.\n4. Call `resources/read` with the resolved URI.\n5. Inject only the context needed for the current task.');
 if(uri==='mcp://studio/security/checklist')return markdownResource(uri,'# MCP security checklist\n\n'+securityChecks.map(x=>`* ${x}`).join('\n'));
 if(uri==='mcp://studio/schemas/tool-result')return jsonResource(uri,{$schema:'https://json-schema.org/draft/2020-12/schema',type:'object',properties:{content:{type:'array'},structuredContent:{type:'object'},isError:{type:'boolean'}},required:['content']},'application/schema+json');
 throw new Error(`Resource not found: ${uri}`);
}

export function createServer(){
 const server=new McpServer({name:'mcp-studio',version:'2.0.0'});
 registerAppTool(server,'show_dashboard',{title:toolDefinitions[0].title,description:toolDefinitions[0].description,inputSchema:emptySchema,annotations:toolDefinitions[0].annotations,_meta:toolDefinitions[0]._meta!},async()=>result({title:'Your plugin, in the conversation',examples,estimate:estimate({requests:1000,latencyMs:250,costPerRequest:0.002})}));
 server.registerTool('get_examples',{title:toolDefinitions[1].title,description:toolDefinitions[1].description,inputSchema:emptySchema,annotations:toolDefinitions[1].annotations},async()=>result({examples}));
 server.registerTool('calculate_estimate',{title:toolDefinitions[2].title,description:toolDefinitions[2].description,inputSchema:estimateSchema,outputSchema:z.object({requests:z.number(),latencyMs:z.number(),costPerRequest:z.number(),totalCost:z.number(),sequentialSeconds:z.number(),currency:z.string(),assumptions:z.string()}),annotations:toolDefinitions[2].annotations},async a=>result(estimate(a)));
 server.registerTool('list_embed_templates',{title:toolDefinitions[3].title,description:toolDefinitions[3].description,inputSchema:emptySchema,annotations:toolDefinitions[3].annotations},async()=>result({templates:dashboardTemplates}));
 registerAppTool(server,'open_template_builder',{title:toolDefinitions[4].title,description:toolDefinitions[4].description,inputSchema:builderSchema,annotations:toolDefinitions[4].annotations,_meta:toolDefinitions[4]._meta!},async (input:z.infer<typeof builderSchema>)=>result({view:'template-builder',selection:{template:input.template??'analytics',theme:input.theme??'light'},templates:dashboardTemplates}));
 server.registerTool('search_catalog',{title:toolDefinitions[5].title,description:toolDefinitions[5].description,inputSchema:searchSchema,annotations:toolDefinitions[5].annotations},async input=>{const query=input.query.toLowerCase();const matches=catalogEntries().filter(x=>(input.kind==='all'||x.kind===input.kind)&&`${x.name} ${x.title} ${x.description}`.toLowerCase().includes(query));return result({query:input.query,kind:input.kind,matches,total:matches.length})});
 server.registerTool('inspect_capabilities',{title:toolDefinitions[6].title,description:toolDefinitions[6].description,inputSchema:emptySchema,annotations:toolDefinitions[6].annotations},async()=>result({referenceSpec:'2025-11-25',tools:toolDefinitions.length,resources:resourceDefinitions.length,resourceTemplates:resourceTemplateDefinitions.length,prompts:promptDefinitions.length,features:{structuredContent:true,outputSchema:true,resourceLinks:true,completion:true,mcpApps:true,subscriptions:false,tasks:false}}));
 server.registerTool('validate_tool_input',{title:toolDefinitions[7].title,description:toolDefinitions[7].description,inputSchema:validateSchema,annotations:toolDefinitions[7].annotations},async input=>{const schema=inputSchemas[input.toolName];if(!schema)return result({valid:false,toolName:input.toolName,errors:['Unknown tool']});const parsed=schema.safeParse(input.input);return result({valid:parsed.success,toolName:input.toolName,errors:parsed.success?[]:parsed.error.issues.map(x=>`${x.path.join('.')||'input'}: ${x.message}`)})});
 server.registerTool('estimate_context_budget',{title:toolDefinitions[8].title,description:toolDefinitions[8].description,inputSchema:budgetSchema,annotations:toolDefinitions[8].annotations},async input=>{const estimatedTokens=input.resourceCount*input.averageTokens;const utilization=Math.round(estimatedTokens/input.contextWindow*10000)/100;return result({...input,estimatedTokens,utilizationPercent:utilization,remainingTokens:Math.max(0,input.contextWindow-estimatedTokens),fits:estimatedTokens<=input.contextWindow*.8,recommendation:estimatedTokens<=input.contextWindow*.8?'Within the 80% context budget.':'Reduce, rank, or summarize resources before injection.'})});
 server.registerTool('plan_workflow',{title:toolDefinitions[9].title,description:toolDefinitions[9].description,inputSchema:workflowSchema,annotations:toolDefinitions[9].annotations},async input=>{const plans={build:['inspect_capabilities','mcp://studio/tools/catalog','design_mcp_tool','validate_tool_input'],audit:['mcp://studio/security/checklist','audit_mcp_server','inspect_capabilities'],debug:['search_catalog','mcp://studio/examples/tool-call','validate_tool_input'],optimize:['estimate_context_budget','mcp://studio/examples/resource-flow','plan_mcp_app']};return result({goal:input.goal,steps:plans[input.goal],humanGate:'Required before adding write tools or sensitive resources.'})});
 server.registerTool('get_resource_examples',{title:toolDefinitions[10].title,description:toolDefinitions[10].description,inputSchema:emptySchema,annotations:toolDefinitions[10].annotations},async()=>({content:[{type:'text' as const,text:JSON.stringify({resources:resourceDefinitions,templates:resourceTemplateDefinitions})},...resourceDefinitions.filter(x=>x.uri.startsWith('mcp://')).slice(0,4).map(x=>({type:'resource_link' as const,uri:x.uri,name:x.name,title:x.title,description:x.description,mimeType:x.mimeType,annotations}))],structuredContent:{resources:resourceDefinitions,templates:resourceTemplateDefinitions}}));
 server.registerTool('get_security_checklist',{title:toolDefinitions[11].title,description:toolDefinitions[11].description,inputSchema:emptySchema,annotations:toolDefinitions[11].annotations},async()=>result({checks:securityChecks,total:securityChecks.length}));

 registerAppResource(server,'starter-dashboard',RESOURCE_URI,{},async()=>({contents:[{uri:RESOURCE_URI,mimeType:RESOURCE_MIME_TYPE,text:widgetHtml,_meta:{ui:{prefersBorder:true,csp:{connectDomains:[],resourceDomains:[]}},'openai/widgetDescription':'Starter dashboard with example patterns and interactive tools.','openai/widgetPrefersBorder':true,'openai/widgetCSP':{connect_domains:[],resource_domains:[]}}}]}));
 for(const definition of resourceDefinitions.filter(x=>x.uri!==RESOURCE_URI))server.registerResource(definition.name,definition.uri,{title:definition.title,description:definition.description,mimeType:definition.mimeType,annotations},async uri=>staticResource(uri.toString()));
 const toolNames=toolDefinitions.map(x=>x.name);const templateIds=dashboardTemplates.map(x=>x.id);const topics=Object.keys(topicDocs);
 server.registerResource('tool-reference',new ResourceTemplate('mcp://studio/tool/{name}',{list:undefined,complete:{name:value=>toolNames.filter(x=>x.includes(value)).slice(0,20)}}),{title:'Tool reference',description:'Detailed reference for one registered tool.',mimeType:'application/json',annotations},async(uri,variables)=>{const name=String(variables.name);const tool=toolDefinitions.find(x=>x.name===name);if(!tool)throw new Error(`Unknown tool: ${name}`);return jsonResource(uri.toString(),tool)});
 server.registerResource('embed-template-reference',new ResourceTemplate('mcp://studio/template/{id}',{list:undefined,complete:{id:value=>templateIds.filter(x=>x.includes(value)).slice(0,20)}}),{title:'Embed template reference',description:'Detailed reference for one dashboard template.',mimeType:'application/json',annotations},async(uri,variables)=>{const id=String(variables.id);const template=dashboardTemplates.find(x=>x.id===id);if(!template)throw new Error(`Unknown template: ${id}`);return jsonResource(uri.toString(),template)});
 server.registerResource('protocol-topic',new ResourceTemplate('mcp://studio/docs/{topic}',{list:undefined,complete:{topic:value=>topics.filter(x=>x.includes(value)).slice(0,20)}}),{title:'Protocol topic guide',description:'Focused MCP implementation guidance.',mimeType:'text/markdown',annotations},async(uri,variables)=>{const topic=String(variables.topic);const doc=topicDocs[topic];if(!doc)throw new Error(`Unknown topic: ${topic}`);return markdownResource(uri.toString(),doc)});

 server.registerPrompt('design_mcp_tool',{title:promptDefinitions[0].title,description:promptDefinitions[0].description,argsSchema:{goal:z.string().min(3).max(500)}},async({goal})=>({description:'Design a narrow MCP tool contract.',messages:[{role:'user',content:{type:'text',text:`Design an MCP tool for this goal: ${goal}\nReturn its name, precise description, JSON Schema input and output, annotations, authorization checks, failure modes, and acceptance tests. Keep the authority narrow.`}}]}));
 server.registerPrompt('audit_mcp_server',{title:promptDefinitions[1].title,description:promptDefinitions[1].description,argsSchema:{focus:z.string().max(200).optional()}},async({focus})=>({description:'Audit an MCP server.',messages:[{role:'user',content:{type:'text',text:`Audit this MCP server for protocol correctness, schema quality, security, privacy, interoperability, latency, and operational readiness.${focus?` Focus on ${focus}.`:''} Separate evidence, inference, and required fixes.`}}]}));
 server.registerPrompt('plan_mcp_app',{title:promptDefinitions[2].title,description:promptDefinitions[2].description,argsSchema:{audience:z.string().min(2).max(200)}},async({audience})=>({description:'Plan a progressively enhanced MCP App.',messages:[{role:'user',content:{type:'text',text:`Plan an MCP App for ${audience}. Define the tool contract, structuredContent, text fallback, UI resource, CSP, host actions, mobile behavior, empty states, security boundaries, and acceptance tests.`}}]}));
 return server;
}
