import fs from 'node:fs';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const esbuild=await import(require.resolve('esbuild',{paths:[require.resolve('vite')]}));
const result=await esbuild.build({entryPoints:['widget/main.ts'],bundle:true,minify:true,format:'iife',platform:'browser',target:'es2022',write:false});
const script=result.outputFiles[0].text.replaceAll('</script','<\\/script');
const html=fs.readFileSync('widget/template.html','utf8').replace('/* WIDGET_SCRIPT */',()=>script);
fs.writeFileSync('lib/widget.generated.ts','// Generated by scripts/build-widget.mjs\nexport const widgetHtml='+JSON.stringify(html)+';\n');
console.log('Widget bundled:',html.length,'bytes');
