import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url);const esbuild=await import(require.resolve('esbuild',{paths:[require.resolve('vite')]}));
const dir=await mkdtemp(tmpdir()+'/mcp-test-');
try{
await esbuild.build({entryPoints:['app/mcp/route.ts'],bundle:true,platform:'node',format:'esm',outfile:dir+'/route.mjs',packages:'bundle'});
const {POST,GET,OPTIONS}=await import(pathToFileURL(dir+'/route.mjs'));
let checks=0;
async function rpc(method,params={}){const res=await POST(new Request('https://example.test/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})}));assert.equal(res.status,200);return res.json()}
const init=await rpc('initialize',{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'acceptance',version:'1'}});assert.equal(init.result.serverInfo.name,'mcp-studio');checks++;
const list=await rpc('tools/list');assert.equal(list.result.tools.length,12);assert.equal(list.result.tools.filter(t=>t._meta?.ui?.resourceUri).length,2);assert.ok(list.result.tools.find(t=>t.name==='calculate_estimate').outputSchema);checks++;
const dash=await rpc('tools/call',{name:'show_dashboard',arguments:{}});assert.equal(dash.result.structuredContent.estimate.totalCost,2);checks++;
const calc=await rpc('tools/call',{name:'calculate_estimate',arguments:{requests:2000,latencyMs:250,costPerRequest:0.002}});assert.equal(calc.result.structuredContent.totalCost,4);assert.equal(calc.result.structuredContent.sequentialSeconds,500);checks++;
const examples=await rpc('tools/call',{name:'get_examples',arguments:{}});assert.equal(examples.result.structuredContent.examples.length,5);checks++;
const templates=await rpc('tools/call',{name:'list_embed_templates',arguments:{}});assert.equal(templates.result.structuredContent.templates.length,5);assert.ok(templates.result.structuredContent.templates.every(t=>t.sourceUrl.startsWith('https://dribbble.com/shots/')));checks++;
const builder=await rpc('tools/call',{name:'open_template_builder',arguments:{template:'fleet',theme:'dark'}});assert.equal(builder.result.structuredContent.selection.template,'fleet');assert.equal(builder.result.structuredContent.selection.theme,'dark');checks++;
const search=await rpc('tools/call',{name:'search_catalog',arguments:{query:'resource',kind:'all'}});assert.ok(search.result.structuredContent.total>=4);checks++;
const capabilities=await rpc('tools/call',{name:'inspect_capabilities',arguments:{}});assert.equal(capabilities.result.structuredContent.tools,12);assert.equal(capabilities.result.structuredContent.resourceTemplates,3);checks++;
const valid=await rpc('tools/call',{name:'validate_tool_input',arguments:{toolName:'calculate_estimate',input:{requests:1000,latencyMs:250,costPerRequest:0.002}}});assert.equal(valid.result.structuredContent.valid,true);checks++;
const invalid=await rpc('tools/call',{name:'validate_tool_input',arguments:{toolName:'calculate_estimate',input:{requests:-1}}});assert.equal(invalid.result.structuredContent.valid,false);checks++;
const budget=await rpc('tools/call',{name:'estimate_context_budget',arguments:{resourceCount:8,averageTokens:1200,contextWindow:128000}});assert.equal(budget.result.structuredContent.estimatedTokens,9600);assert.equal(budget.result.structuredContent.fits,true);checks++;
const workflow=await rpc('tools/call',{name:'plan_workflow',arguments:{goal:'audit'}});assert.equal(workflow.result.structuredContent.steps[0],'mcp://studio/security/checklist');checks++;
const links=await rpc('tools/call',{name:'get_resource_examples',arguments:{}});assert.equal(links.result.content.filter(x=>x.type==='resource_link').length,4);checks++;
const checklist=await rpc('tools/call',{name:'get_security_checklist',arguments:{}});assert.equal(checklist.result.structuredContent.total,10);checks++;
const bad=await rpc('tools/call',{name:'calculate_estimate',arguments:{requests:-1,latencyMs:250,costPerRequest:0.002}});assert.ok(bad.result?.isError||bad.error);checks++;
const unknown=await rpc('tools/call',{name:'unknown',arguments:{}});assert.ok(unknown.result?.isError||unknown.error);checks++;
const resources=await rpc('resources/list');assert.equal(resources.result.resources.length,8);assert.ok(resources.result.resources.some(x=>x.uri==='mcp://studio/manifest'));checks++;
const resource=await rpc('resources/read',{uri:'ui://starter/dashboard.html'});assert.equal(resource.result.contents[0].mimeType,'text/html;profile=mcp-app');assert.ok(resource.result.contents[0].text.includes('estimate-form'));checks++;
const manifest=await rpc('resources/read',{uri:'mcp://studio/manifest'});const manifestData=JSON.parse(manifest.result.contents[0].text);assert.equal(manifestData.counts.tools,12);checks++;
const resourceTemplates=await rpc('resources/templates/list');assert.equal(resourceTemplates.result.resourceTemplates.length,3);checks++;
const toolReference=await rpc('resources/read',{uri:'mcp://studio/tool/calculate_estimate'});assert.equal(JSON.parse(toolReference.result.contents[0].text).name,'calculate_estimate');checks++;
const completion=await rpc('completion/complete',{ref:{type:'ref/resource',uri:'mcp://studio/tool/{name}'},argument:{name:'name',value:'get_'}});assert.ok(completion.result.completion.values.includes('get_examples'));checks++;
const prompts=await rpc('prompts/list');assert.equal(prompts.result.prompts.length,3);checks++;
const prompt=await rpc('prompts/get',{name:'design_mcp_tool',arguments:{goal:'Build a governed search tool'}});assert.match(prompt.result.messages[0].content.text,/governed search tool/);checks++;
const origin=await POST(new Request('https://example.test/mcp',{method:'POST',headers:{Origin:'https://chatgpt.com','Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/list'})}));assert.equal(origin.status,200);assert.equal(origin.headers.get('access-control-allow-origin'),'*');checks++;
const preflight=OPTIONS();assert.equal(preflight.status,204);assert.match(preflight.headers.get('access-control-allow-headers')??'',/MCP-Protocol-Version/);checks++;
const huge=await POST(new Request('https://example.test/mcp',{method:'POST',headers:{'Content-Type':'application/json'},body:'x'.repeat(32769)}));assert.equal(huge.status,413);checks++;
const malformed=await POST(new Request('https://example.test/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:'{bad'}));assert.equal(malformed.status,400);checks++;
assert.equal(GET().status,405);checks++;
console.log(`${checks} protocol and security checks passed`);
}finally{await rm(dir,{recursive:true,force:true})}
